### ISSUE TITLE
use js file

### ISSUE THREAD

**Issue by rahulmodu** [fulls1z3/universal#125]
where to add  .js files of external library to make it a part of chunk or bundle

**Comment by rahulmodu** [comment]
where to add .js files of external library to make it a part of chunk or bundle, how can be done.

**Comment by fulls1z3** [comment]
@rahulmodu you have to include those libraries within the application code in order to be bundled.

If that's not the case, use the **html-elements-webpack-plugin** by adding the required library's URL to `tools/config/html-elements-config.js`. This way you *js* library can be called via CDN or external source. 

You can find more information about **html-elements-webpack-plugin** on https://github.com/fulls1z3/html-elements-webpack-plugin. That plugin is already included by **angular-webpack-config**, you don't need to configure/add it to plugins array of *webpack* configuration.
