### ISSUE TITLE
how to deploy

### ISSUE THREAD

**Issue by vlados** [fulls1z3/universal#162]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[x] Documentation issue or request
```
So, how I can use the stack in production environment?
If I run npm run serve and setup nginx to use upstream localhost:8000 is it going to be ok?
And is it doing initial server rendering and then loading the SPA for better UX?

**Comment by fulls1z3** [comment]
@vlados it depends, my friend. On azure - I had to replace all occurrences of `8000` (*or `8k3` - when minfied*) with `process.env.PORT` - because of the limitations of IISNODE.

I'll have a try on other platforms including Heroku, Google Cloud Platform, and AWS - and I'll also try to trigger a deploy via Github/CircleCI, and then share the knowledge on the README together with the deploy/publish scripts.

Meanwhile, on which platform were you planning to deploy? Also, feel free to share your experiences, they will be highly appreciated 👍

**Comment by vlados** [comment]
I am doing it on DigitalOcean and I will do everything manually to understand the process and after that I can make some scripts for automation. 
So I have the ready to use application with npm run build:universal-prod and if I run server.js is doing the first request with server rendering and after this everything is like a normal SPA?

**Comment by fulls1z3** [comment]
Honestly I have no information about DigitalOcean but as long as you use an express server, should work the way you mentioned.

**Comment by aneeshkumar-klr** [comment]
How to deploy ng-seed/universal application in heroku ?
Anyone please..

**Comment by vlados** [comment]
https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction
You are deploying it as normal node.js app
