### ISSUE TITLE
add HMR support

### ISSUE THREAD

**Issue by IPRIT** [fulls1z3/universal#2]
Do you have any plans to do it for real time developing? 
At the moment it takes too much time for compiling new bundles and serving in a browser.
I think all of us wants to see best performance in building and new nice features like HMR, etc. (what we see in [@AngularClass/angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter))
Because of this fact above it becomes useless example although you made great work!

**Comment by fulls1z3** [comment]
Hi @IPRIT, thanks for pointing out this topic.

Actually I was thinking about the same thing on the way home from gym - so, great minds think alike ;)

Although it's less than just a couple of hours of work, this week I won't be able to provide that. But within a week or two, for sure I'll publish an update containing the HMR functionality.

**Comment by wozniakm** [comment]
Hi! Anything new on this request? 

Great work, man 👍

**Comment by fulls1z3** [comment]
Hi @wozniakm, thanks for your appreciation 👍 

Just updated the repo with some utils from @nglibs and their loaders at the server-side, and currently working on caching the XHR/fs requests.

I think after this, HMR has the first priority - so we're not far from there. And then I hope I'll make several contributions to @angular/universal with these lessons learned.

**Comment by wozniakm** [comment]
Sounds great. If you can prepare some roadmap I would love to help you with developing that "starter" pack.

**Comment by fulls1z3** [comment]
Thanks @wozniakm, I and all people benefiting from this repo would really appreciate that.

Currently we've got more or less no roadmap, except the items on the issue list. Feel free to add new items with `enhancement` tag/label, so I will do that and let's progress with them.

Actually, just after the cache implementation new items will occur.

**Comment by mohamed-rekiba** [comment]
Hi @fulls1z3, is there any new news?

**Comment by fulls1z3** [comment]
Hi @MuhammadShaban, I made a few tries on it.

First tried the HMR from @AngularClass, but it simply didn't work. Then made another try using `webpack-hot-middleware`. Seemed like it was working, but it simply re-triggers the webpack process from all over.

I've read the issues about `webpack-hot-middleware` and they say it could happen because we use `nodemon`. So basically it would take a few more time until we got it running.

Meanwhile, I didn't commit that code because it would create a huge mess for the people who are already benefiting from this repo. If you're interested I can hereby share a zipped version of this repo and you can create a PR if you have the opportunity.

**Comment by fulls1z3** [comment]
hi @IPRIT @MuhammadShaban @wozniakm, just pushed the latest changes including HMR support. Refer the instructions at the README and give it a try when u've got available time. Awaiting feedbacks 👍

**Comment by mohamed-rekiba** [comment]
thanks @IPRIT, i will try it as soon as possible.
