### ISSUE TITLE
fail to uglify on some es6 code

### ISSUE THREAD

**Issue by Vikasbansal1234** [fulls1z3/universal#83]
I am using socke-io in my project the build is created successfully when i run command npm run build:universal-dev but it is not creating build on production please can u tell me the what the exact issue is :: Here is Err::

**Error: server.js from UglifyJs
Unexpected token: name (PerMessageDeflate) [server.js:53927,6]

    (1) error(s) total.**

**Comment by rahulmodu** [comment]
I have same issue , if you will get any solution then reply me

**Comment by fulls1z3** [comment]
@Vikasbansal1234 @rahulmodu it's **UglifyJS**, even though I suffered from it much. Usually it happens when there's some kinda ES6 code that **UglifyJS** cannot process.

It appears that we need to plan a smooth transition from **UglifyJS** to **UglifyES**, otherwise we'll hear more from this issue.

I convert this issue to type *bug*, going to track it here and announce everyone when a fix is gonna be published.

Meanwhile, feel free to share some more details about your environment (*Angular and NodeJS version, deps in your package.json, etc*) which will be very useful to reproduce this.

**Comment by Vikasbansal1234** [comment]
Hey,
I have migrated my code from angular-cli to ng-seed ,but I am not able to make proudction build can u help me how can i replace the uglifyjs to uglifyes so that i can deploy my code to production.

**Comment by fulls1z3** [comment]
@Vikasbansal1234 @rahulmodu updated the project using **uglifyes**, which accepts es6 code. Pull the changes and give it a try, and then let me know about the status guys.
